PKG_NAME="mqtt-client"
PKG_VER="1.0.0-r1"
PKG_DESC="Lightweight MQTT CLI Client Tools (mqtt-pub and mqtt-sub)"
PKG_ARCH="xtensa"
PKG_URL="https://github.com/canusdev/esp-linux"
PKG_LICENSE="MIT"
PKG_DEPS=""
