PKG_NAME="dash"
PKG_VER="0.5.12-r1"
PKG_DESC="Fast POSIX-compliant shell with minimal memory footprint"
PKG_ARCH="xtensa"
PKG_URL="http://gondor.apana.org.au/~herbert/dash/"
PKG_LICENSE="BSD-3-Clause"
PKG_DEPS=""
